### ISSUE TITLE
[1.14.4] Server crash - ReportedException: Ticking block entity

### ISSUE THREAD

**Issue by ProsperCraft** [TheMCBrothers/UselessMod#11]
**Describe the bug**
Server crashed, I think it may be related to the .40 forge update.

It was working fine, I built out my machine room, and when the server locked up due to Ruins, and I killed the process, it came back up and crashed when I logged in.

Stacktrace in console=
https://gist.github.com/ProsperCraft/d0c3fa91ce74366245c52efad6064c5d

Crash log-
https://gist.github.com/ProsperCraft/340e606c281b264e448083a802f22d1f

When I rebooted, it didn't crash.

**Forge Version** forge-1.14.4-28.1.40
**Mod Version**UselessMod-1.14.4-2.2.4
**Modpack** https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by ProsperCraft** [comment]
After this crash my energy network quit working.

**Comment by ProsperCraft** [comment]
Fixed by replacing cables.

**Comment by ProsperCraft** [comment]
![2019-10-08_18 08 29](https://user-images.githubusercontent.com/4427684/66442120-bafed400-e9f6-11e9-92fd-60b08a78a21c.png)
This may be related.

**Comment by TheMCBrothers-Manager** [comment]
I have rewritten the entire energy cable code.
It still does not work 100% correctly, but it will be enough for the next update.
This bug should be fixed in 1.14.4-2.2.5

![2019-10-09_17 26 36](https://user-images.githubusercontent.com/50276703/66495795-2362b980-eaba-11e9-937e-45029e3b302a.png)
